### ISSUE TITLE
关于运行评估evaluation

### ISSUE THREAD

**Issue by Razliublt** [qingzhenduyu/ICAL#1]
# For CROHME Dataset
bash eval/eval_crohme.sh 0

# For HME100K Dataset
bash eval/eval_hme100k.sh 1
这是redme的步骤，但是代码文件中似乎缺少eval/eval_crohme.sh 0 和eval/eval_hme100k.sh 1，eval文件夹中只有test.py,可以用test.py进行评估测试吗

**Comment by qingzhenduyu** [comment]
We have added eval_crohme.sh and eval_hme100k.sh in newest commit. Thanks!
