### ISSUE TITLE
在复现ICAL实验过程中遇到一些问题

### ISSUE THREAD

**Issue by Kerston12138** [qingzhenduyu/ICAL#3]
作者你好 ！ 我在复现你们项目的时候遇到一些基础的问题 盼望您有空的解答

1、训练好的权重文件 保存在哪里？
2、怎么用训练好的 权重 去对单张图片做预测？
3、对单张图片做预测的话 怎么分别查看 ICAL 和 ICCM的预测结果？
4、在model->decoder.py中 SCCM 这里主要的目的是什么，在论文中没有写。

**Comment by qingzhenduyu** [comment]
Hello, 
q1,q2: It is recommended to refer to the official Lightning documentation for learning: [Lightning Documentation](https://lightning.ai/docs/pytorch/stable/).
 For further guidance, please consult the official Lightning documentation.
q3: You can simply refine the `eval/test.py` script for a few lines.
q4:" SCCM is a Transformer Encoder designed to predict implicit tokens, and it has been renamed as ICCM in our paper.

Thanks

**Comment by Kerston12138** [comment]
下午好 师兄


&nbsp; &nbsp; &nbsp; &nbsp;我叫牟世奇，目前是23级硕士研究生 ,也在研究HMER任务，在研究中遇到几个疑惑，没能弄明白。 所以给您写信，请师兄指教一下。

问题描述如下：


1· crohme数据集的vocab_size=114 但是我在data-&gt;crohme-&gt;dictionary.txt中只看到了110个字符,请问 还有四个是什么字符呢？


2· 这些字符与目标序列的编码映射关系是什么？我尝试打印了tgt的内容 发现如果按照dictionary的顺序映射并不能组成一个合理的公式。



期待您的回信 感谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qingzhenduyu/ICAL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月27日(星期一) 晚上11:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qingzhenduyu/ICAL] 在复现ICAL实验过程中遇到一些问题 (Issue #3)





 
Hello,
 q1,q2: It is recommended to refer to the official Lightning documentation for learning: Lightning Documentation.
 For further guidance, please consult the official Lightning documentation.
 q3: You can simply refine the eval/test.py script for a few lines.
 q4:" SCCM is a Transformer Encoder designed to predict implicit tokens, and it has been renamed as ICCM in our paper.
 
Thanks

**Comment by qingzhenduyu** [comment]
1. 你可以参照ICAL/ical/datamodule/vocab.py来找到另外四个字符；
2. 如果你加上这4个字符，是不是就合理了？ 另外，建议直接`indices2words`函数来进行映射，会方便一点。
祝好！
Jianhua Zhu
