### ISSUE TITLE
Some wrong in vocab

### ISSUE THREAD

**Issue by JackJi12316** [qingzhenduyu/ICAL#5]
When I run eval/test.py, it throw the error as (with data of crohme):
KeyError: '-'

but in vocab.py, through test, it is nothing wrong, so I modify vocab.py
before:
```python
def words2indices(self, words: List[str]) -> List[int]:
        return [self.word2idx[w] for w in words]
```
after:
```python
    def words2indices(self, words: List[str]) -> List[int]:
        indices = []
        for w in words:
            if w in self.word2idx:
                indices.append(self.word2idx[w])
            elif w == '-':
                indices.append(9) # only corhme
        return indices
```

And it works. I think there are some thing wrong in vocab, expecally in '-' only.

**Comment by qingzhenduyu** [comment]
In fact, I haven't met this error ever. Maybe you modified the dictionary in CROHME dataset?
