### ISSUE TITLE
创建自己的数据集遇到的问题

### ISSUE THREAD

**Issue by Razliublt** [qingzhenduyu/ICAL#7]
我使用了之前问题中创建数据集的代码，
![image](https://github.com/user-attachments/assets/d835ab1b-0b66-4058-ab23-853c0d6deb88)
我创建了images.pkl但是没有caption.txt,我自己进行了标注后运行test.py 发现问题出在了
![image](https://github.com/user-attachments/assets/4b6715a2-b519-4be9-8063-ed80584be4a0)
请问数据集要如何正确生成

**Comment by Razliublt** [comment]
File "/home/ICAL-main/ICAL-main/ical/datamodule/vocab.py", line 27, in <listcomp>
return [self.word2idx[w] for w in words]
KeyError: '-1'上面那个问题解决了，但是我发现自己标注了caption.txt会报这个错误，我使用了两张图片做了一个数据集想测试一下，如下面所示，caption.txt也如下所示，请问是不是在标注的时候有规则？
![image](https://github.com/user-attachments/assets/4d3b6880-87ae-47c6-a8a9-46fdbe91d6a3)
![image](https://github.com/user-attachments/assets/b2c25626-e210-4400-8be0-1c815e0ff26f)

**Comment by qingzhenduyu** [comment]
@Razliublt train_86”的标注“x+5>-1”中的每个token都应该有空格隔开，即“x + 5 > - 1”，你可以修改试试。

**Comment by Razliublt** [comment]
确实是这个问题，麻烦再问一下最后pred.json中的内容似乎不对
![image](https://github.com/user-attachments/assets/af8f5931-9ab6-407a-89de-0e927d767e53)
出现了这种问题，完整的json文件如下{"train_91.jpg": {"pred": "m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m m } }", "gt": "x < 4", "dist": 199, "im_tokens": "<space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space>"}, "train_86.jpg": {"pred": "m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log \\log \\log \\log \\log \\log \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m m m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m \\log m", "gt": "x + 5 > - 1", "dist": 199, "im_tokens": "<space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space> <space>"}}

**Comment by Razliublt** [comment]
![image](https://github.com/user-attachments/assets/f593ab79-c25f-4c3e-91c1-9f0949c7a730)
同时zai在执行test.py文件时上面的进度条会卡住不动，过一会就恢复原状，最后输出的pred.json和error.json似乎都是上面所示的内容，请问能告知大概是哪块出现了问题

**Comment by qingzhenduyu** [comment]
可能是图片分辨率的问题，调整一下图片分辨率（如适当缩小会好一些）
